### ISSUE TITLE
Unable to use pg-to-ts with typescript 5.0.4

### ISSUE THREAD

**Issue by muesli-dev** [danvk/pg-to-ts#31]
i cant add pg-to-ts to my project, because the typescript reference is too old and i dont want to force npm to do that.
![image](https://user-images.githubusercontent.com/101059217/231807187-5a6b09d2-8b93-4a7e-a306-69a247279466.png)

is there any possbilty that these references can get updated?

**Comment by danvk** [comment]
This was released as 4.1.1. pg-to-ts has always been compatible with TS 5.x, it's just that TS doesn't follow the usual rules around semantic versioning.
